### PR TITLE
add cors config and shard info

### PR DESCRIPTION
**Pull request by odd-man**
1. add cors config
2. add shard info and config

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/9)

### CODE REVIEW

**Comment by mayongxing1983** [comment]
Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 38 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJbNxI4vnFZ-8o0etV:-LEJbNxJDl_fjCVZbn1f:b-ywa4ok) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/README.md#L38)):*
> ```Markdown
> make
> # execute the file
> build/monitor-api start -c <configfile> -s <shard file>
> ```

no need new param, only need to add monitor websocket config file and point to the file in start configfile

---

*[cmd/api/cmd/start.go, line 67 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJdmSKBapKaYXsmbER:-LEJdmSKBapKaYXsmbES:b-to1qog) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/cmd/api/cmd/start.go#L67)):*
> ```Go
> 
> 	shardFile = startCmd.Flags().StringP("shard", "s", "", "api shard config file (required)")
> 	startCmd.MarkFlagRequired("shard")
> ```

same as last comment, no need new param in command

---

*[cmd/api/config/app2.conf, line 47 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJeAJ92xLXxhXz3aG9:-LEJeAJ92xLXxhXz3aGA:b5lxe79) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/cmd/api/config/app2.conf#L47)):*
> ```
> 
> # log level, debug, info, warn, error, fatal, panic
> LogLevel = debug
> ```

delete it 

---

*[cmd/api/config/app3.conf, line 46 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJeCBXDVohqNpd6a49:-LEJeCBXDVohqNpd6a4A:b-kfvgdh) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/cmd/api/config/app3.conf#L46)):*
> ```
> RPCURL = 127.0.0.1:55029
> 
> # log level, debug, info, warn, error, fatal, panic
> ```

delete it

---

*[cmd/api/config/shard.json, line 5 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJeEIa5lWKG12d1dhk:-LEJeEIa5lWKG12d1dhl:b-o3ywlu) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/cmd/api/config/shard.json#L5)):*
> ```JSON
>     "2":"127.0.0.1:9998",
>     "3":"127.0.0.1:9999",
>     "4":"127.0.0.1:9996",
> ```

it should be same as follows

---

*[ws/seele_stats.go, line 37 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJf82D2gluBRFQ7N7D:-LEJf82D2gluBRFQ7N7E:b-m81g79) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/ws/seele_stats.go#L37)):*
> ```Go
> 	host     string // Remote address of the monitoring service
> 	port     int    // monitor api port
> 	shard    uint
> ```

add comment

---

*[ws/seele_stats.go, line 66 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJg-VOBMrE8awjOv8I:-LEJg-VOBMrE8awjOv8J:b-kojxap) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/ws/seele_stats.go#L66)):*
> ```Go
> 		logs.Error("shard config error, shard %v not exist web socket url", shard)
> 		return nil, err
> 	}
> ```

websocketURL may be ''

---

*[ws/seele_stats.go, line 522 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJoD4YEnvSyDj6Ecz8:-LEJmgnZC3jIdTby19qm:bwr12c8) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/ws/seele_stats.go#L522)):*
> ```Go
> 	delete(info, "shard")
> 	delete(block, "shard")
> 	delete(stats, "shard")
> ```

no need these delete

---

*[ws/seele_stats.go, line 577 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJo77b2ZTHuFwUL8V5:-LEJo77b2ZTHuFwUL8V6:b-zhteyi) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/ws/seele_stats.go#L577)):*
> ```Go
> 			"syncing":    false,
> 			"netVersion": s.currentNetVersion,
> 			"shard":      s.shard,
> ```

shard & netVersion should out of stats struct

---

*[cmd/api/config/app1.conf, line 63 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJdw72Aq20SPH0tpBc:-LEJdw72Aq20SPH0tpBd:b-l4r5bo) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/cmd/api/config/app1.conf#L63)):*
> ```
> RPCUrl = 127.0.0.1:55027
> # debug, info, warn, error, fatal, panic
> LogLevel = debug
> ```

no need new three app.conf file, it is ok to give one example file

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/9)*

**Comment by odd-man** [comment]
Review status: 0 of 14 files reviewed at latest revision, 10 unresolved discussions.

---

*[cmd/api/cmd/start.go, line 67 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJdmSKBapKaYXsmbER:-LEJtV5a1GhOpsthscol:b-896fix) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/cmd/api/cmd/start.go#L67)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

same as last comment, no need new param in command
</blockquote></details>

Done.

---

*[ws/seele_stats.go, line 37 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJf82D2gluBRFQ7N7D:-LEJtSsaA4YnKCRp2K-A:b-896fix) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/ws/seele_stats.go#L37)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

add comment
</blockquote></details>

Done.

---

*[ws/seele_stats.go, line 66 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJg-VOBMrE8awjOv8I:-LEJtSHe6mTVq06f5-FQ:b-896fix) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/ws/seele_stats.go#L66)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

websocketURL may be ''
</blockquote></details>

Done.

---

*[ws/seele_stats.go, line 522 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJoD4YEnvSyDj6Ecz8:-LEJtRuFE_ZVwG6xqtBq:b-896fix) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/ws/seele_stats.go#L522)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

no need these delete
</blockquote></details>

Done.

---

*[ws/seele_stats.go, line 577 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJo77b2ZTHuFwUL8V5:-LEJtS6E2mvCVLjPtooq:b-896fix) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/ws/seele_stats.go#L577)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

shard & netVersion should out of stats struct
</blockquote></details>

Done.

---

*[README.md, line 38 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJbNxI4vnFZ-8o0etV:-LEJsnJdB1nve69DUTD5:b-896fix) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/README.md#L38)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

no need new param, only need to add monitor websocket config file and point to the file in start configfile
</blockquote></details>

Done.

---

*[cmd/api/config/app1.conf, line 63 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJdw72Aq20SPH0tpBc:-LEJtTV48TDPOvDUdCci:b-896fix) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/cmd/api/config/app1.conf#L63)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

no need new three app.conf file, it is ok to give one example file
</blockquote></details>

Done.

---

*[cmd/api/config/app2.conf, line 47 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJeAJ92xLXxhXz3aG9:-LEJtPv02HFNfv2j4Z-0:b-896fix) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/cmd/api/config/app2.conf#L47)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

delete it 
</blockquote></details>

Done.

---

*[cmd/api/config/app3.conf, line 46 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJeCBXDVohqNpd6a49:-LEJtP-jEf5aooa39zP7:b-896fix) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/cmd/api/config/app3.conf#L46)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

delete it
</blockquote></details>

Done.

---

*[cmd/api/config/shard.json, line 5 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LEJeEIa5lWKG12d1dhk:-LEJtPMh3FJYa4vljKNX:b-896fix) ([raw file](https://github.com/seeleteam/monitor-api/blob/6150692b1691744f7a34ea5ecd58c5f998461548/cmd/api/config/shard.json#L5)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

it should be same as follows
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/9)*

**Comment by webbergao1** [comment]
Reviewed 8 of 18 files at r1, 101 of 109 files at r2.
Review status: 106 of 113 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/9)*

**Comment by webbergao1** [comment]
Reviewed 1 of 18 files at r1, 3 of 109 files at r2.
Review status: 109 of 113 files reviewed at latest revision, 10 unresolved discussions.

---

*[Dockerfile, line 30 at r2](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LESH3kg-dOIeLO4fztX:-LESH3kg-dOIeLO4fztY:b-hv7wd0) ([raw file](https://github.com/seeleteam/monitor-api/blob/2fcb331636dcabd27f6da5d2fc157416cfac9a24/Dockerfile#L30)):*
> ```Dockerfile
> # start monitor-api with your 'app.conf' file, this file must be external from a volume
> # For example:
> #   docker run -v <your app.conf path>:/monitor-api/config/app.conf:ro -it monitor-api
> ```

this example should be update

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/9)*

**Comment by webbergao1** [comment]
Reviewed 1 of 109 files at r2.
Review status: 111 of 113 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/9)*

**Comment by webbergao1** [comment]
Review status: 111 of 113 files reviewed at latest revision, 11 unresolved discussions.

---

*[README.md, line 57 at r2](https://reviewable.io/reviews/seeleteam/monitor-api/9#-LESHj5WA2S2x8f1u3rH:-LESHj5WA2S2x8f1u3rI:b-98e5mg) ([raw file](https://github.com/seeleteam/monitor-api/blob/2fcb331636dcabd27f6da5d2fc157416cfac9a24/README.md#L57)):*
> ```Markdown
> 
> ```bash
> docker run -v <your app.conf path>:/monitor-api/config:ro -it monitor-api
> ```

<you app.conf dir>

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/9)*

**Comment by webbergao1** [comment]
Reviewed 1 of 109 files at r2.
Review status: 112 of 113 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/9)*

**Comment by webbergao1** [comment]
Reviewed 1 of 109 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/9)*

**Comment by mayongxing1983** [comment]
Reviewed 9 of 18 files at r1, 104 of 109 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/9)*

**Pull request merged**
