### PR TITLE
monitor-api api is ok

### PR DESCRIPTION
**Pull request by odd-man**
monitor api based gin is ok

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/5)

### CODE REVIEW

**Comment by webbergao1** [comment]
Reviewed 3 of 35 files at r1.
Review status: 3 of 35 files reviewed at latest revision, all discussions resolved.

---

*[api/http_metod.go, line 5 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/5#-LCbHgIXClmpDb3Yi-Xp:-LCbHgIXClmpDb3Yi-Xq:b-snq0fw) ([raw file](https://github.com/seeleteam/monitor-api/blob/e8f6841b51a4cc512ced12fcdd6cdab9bb5b5be0/api/http_metod.go#L5)):*
> ```Go
> *  @copyright defined in monitor-api/LICENSE
>  */
> ```

Misspelled file name ‘metod’

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/5)*

**Comment by odd-man** [comment]
Review status: 3 of 35 files reviewed at latest revision, 1 unresolved discussion.

---

*[api/http_metod.go, line 5 at r1](https://reviewable.io/reviews/seeleteam/monitor-api/5#-LCbHgIXClmpDb3Yi-Xp:-LCbWBaf1Bz073leQHPJ:b-7ql1td) ([raw file](https://github.com/seeleteam/monitor-api/blob/e8f6841b51a4cc512ced12fcdd6cdab9bb5b5be0/api/http_metod.go#L5)):*
<details><summary><i>Previously, webbergao1 (weibogao) wrote…</i></summary><blockquote>

Misspelled file name ‘metod’
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/5)*

**Comment by jessonzheng** [comment]
Reviewed 34 of 36 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/5)*

**Comment by jessonzheng** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/5)*

**Comment by webbergao1** [comment]
Reviewed 2 of 36 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/monitor-api/5)*

**Pull request merged**
